Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SignalException:
  EnforcedStyle: semantic
