language: ruby

rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0

cache: bundler

before_install: gem update --system

after_success: bundle exec codeclimate-test-reporter

notifications:
  email:
    on_success: never
    on_failure: change
