language: ruby

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1

cache: bundler

sudo: false

after_success: bundle exec codeclimate-test-reporter

notifications:
  email:
    on_success: never
    on_failure: change
