name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - 'jruby-9.4'
    env:
      BUNDLE_WITHOUT: development
      JRUBY_OPTS: '--debug'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby-version}}
        bundler-cache: true
    - name: Run build
      run: bundle exec rake
    - name: Publish code coverage
      if: ${{matrix.ruby-version == '3.2'}}
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: 31bb2587ede36483fc8c0bb5d3916ec62c7706d3b5080ab6eb7e465c728382ca
