name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: development
      JRUBY_OPTS: '--debug'
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - 'jruby-9.4'
          - 'jruby-head'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby-version}}
        bundler-cache: true
    - name: Run build
      run: bundle exec rake
    - name: Publish code coverage
      if: ${{matrix.ruby-version == '3.2' && github.ref == 'refs/heads/master'}}
      uses: paambaati/codeclimate-action@v3.2.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
