name: Run build

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.3', '2.4', '2.5', '2.6', 'jruby-9.1']
    env:
      BUNDLE_WITHOUT: development
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby-version}}
        bundler-cache: true
    - name: Run build
      run: bundle exec rake
